---
- hosts: all
  tasks:
  - name: test
    command: echo "Hello world"

  - copy:
      src: ansdepl.sh
      dest: /usr/libexec/ansdepl/ansdepl.sh
      owner: root
      group: root
      mode: 0700

  - file:
      path: /media/test
      state: directory
      owner: test
      group: test

  - lineinfile:
      dest: /etc/default/grub
      regexp: 'GRUB_GFXMODE='
      line: 'GRUB_GFXMODE=800x600'
