---
- hosts: all
  tasks:
  - name: test
    command: echo "Hello world"

  - file:
      path: /media/test
      state: directory
      owner: test
      group: test

  - lineinfile:
      dest: /etc/default/grub
      regexp: 'GRUB_GFXMODE='
      line: 'GRUB_GFXMODE=800x600'

